services:
  postgres:
    image: postgres:14.4
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - orders-manager-postgres:/var/lib/postgresql/data

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_SETTINGS_MODULE: "main.settings"
      DB_HOST: postgres
      DB_PORT: 5432
      WAITING_DATABASE: "true"
      MIGRATE: "true"
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    depends_on:
      - postgres

volumes:
  orders-manager-postgres:
