# Generated by Django 4.1 on 2022-08-16 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoreAccount",
            fields=[
                (
                    "token",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("path", models.CharField(max_length=150)),
                ("name", models.CharField(max_length=100)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WarehouseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=100)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Created"),
                            (2, "In process"),
                            (3, "Arrived"),
                            (4, "Failed"),
                        ]
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "store_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="orders",
                        to="warehouse.storeaccount",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
